### ISSUE TITLE
STT0050: update time format in catalog for each department.

### ISSUE THREAD

**Issue by gangagyatso4364** [OpenPecha/stt_utils#1]
### Description
we need to change time format in catalog with a uniform standard format in catalog for each department. This will help us in calculation of audio duration uploaded and duration of audio still left to upload.

all the catalog sheets are here: 
[stt catalogs](https://github.com/OpenPecha/stt-documentation/wiki)

### Completion Criteria
All department catalog with standard time format to show audio duration.
### Subtask
- [x]  create script to change time format and push the script to repo. 
- [x] update time format in NS department catalog.
- [x]  update time format in NS_P department catalog. 
- [x]  update time format in TT department catalog.
- [x]  update time format in CS department catalog.
- [x]  update time format in MV department catalog.
- [x]  update time format in AB department catalog.
- [x]  update time format in PC department catalog.
- [x]  update time format in HS department catalog.
- [x]  update time format in NW department catalog.

**Comment by gangagyatso4364** [comment]
running the script on all departments.

**Comment by gangagyatso4364** [comment]
youtube time format and regex time format update done. drive link time format need to download audio to get timer.
